Header header

float32 x
float32 y
bool[] border # 0000 denotes no border insight, 1000 denotes only green border is insight.


#   _______green_border_0________
#   |                           |
#   |                           |
#   |                           |
#   white_border_3           white_border_1               
#   |                           |
#   |                           |
#   |                           |
#   _______red_border_2__________